### ISSUE TITLE
Suggestion for less orderdetails

### ISSUE THREAD

**Issue by ferryvandegraaf** [happy-geeks/geeks-core-library#490]
The orderdetails are always extended with the 'isTestOrder' property, this is not needed. It would be better to set this to an empty string (and therefore it will not be saved) if the order is NOT a test order. Now all valid orders get a property with value 0.

See this lines of code:
![image](https://github.com/happy-geeks/wiser/assets/15887825/3508f35a-5639-4793-94af-2c15e9cd8275)

I can change this and send a pull request, but i want to check first if it willl be an accepted change, otherwise it will have no use to do the pullrequest. I think there will be no backward compaitbility issues because the GCL never checks on this property.

**Comment by GilianJuice** [comment]
I agree with this change, there is indeed not much point of saving `isTestOrder` with value `0`, because that is the default. If you want to make a PR for this, we'll approve it.
